modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "LGPL-3.0-only"

[[mods]]
modId = "spreadspawnpoints"
version = "${version}"
displayName = "Spread Spawnpoints"
authors = "verarr"
description = '''
Spread all new players around the world in various ways
'''
#logoFile = ""

[[dependencies.spreadspawnpoints]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spreadspawnpoints]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spreadspawnpoints]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
