package xyz.verarr.spreadspawnpoints.spawnpoints;

import org.joml.Vector2i;

public interface SpawnPointGenerator extends NBTSerializable {
    /**
     * Generate a new spawnpoint and return it.
     *
     * @return the generated spawnpoint coordinates.
     */
    Vector2i next();
    /**
     * Test if a spawnpoint is valid, as in it may be generated by this generator.
     *
     * @param spawnPoint spawnpoint to test
     *
     * @return true if the spawnpoint may be generated by this generator, false otherwise.
     */
    boolean isValid(Vector2i spawnPoint);

    /**
     * Internal method to add a spawnpoint to the generator. Only use this if necessary.
     *
     * Implementations may ignore this method.
     *
     * @param spawnPoint spawnpoint to add
     */
    void add(Vector2i spawnPoint);
    /**
     * Internal method to remove a spawnpoint from the generator. Only use this if necessary.
     *
     * Implementations may ignore this method.
     *
     * @param spawnPoint spawnpoint to remove
     */
    void remove(Vector2i spawnPoint);
}
